name: SCA Tool API run
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      #      - name: Upload files to SCA Tool and start scan on Staging
      #        uses: scatool/github-action@v0.2
      #        with:
      #          api_url: http://10.131.64.80/api/v1
      #          api_key: ${{ secrets.SCA_TOOL_API_KEY_STAGING }}
      #          code_unit_id: ""

      - name: Upload files to SCA Tool and start scan on Testing
        uses: scatool/github-action@main
        with:
          api_url: http://localhost:7070/api/v1/
          api_key: ${{ secrets.SCATOOL_API_KEY }}
          code_unit_id: "c856d6f5-baa2-4bfb-9f8f-b46ee72eb3a9"
          github_token: ${{ secrets.GITHUB_TOKEN }}
