name: SCA Tool API run
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      #      - name: Upload files to SCA Tool and start scan on Staging
      #        uses: scatool/github-action@v0.2
      #        with:
      #          api_url: http://10.131.64.80/api/v1
      #          api_key: ${{ secrets.SCA_TOOL_API_KEY_STAGING }}
      #          code_unit_id: ""

      - name: Upload files to SCA Tool and start scan on Locally
        uses: scatool/github-action@v0.4.3
        with:
          api_url: http://localhost:7070/api/v1/
          api_key: ${{ secrets.SCATOOL_API_KEY }}
          project_id: "a031a6a2-a457-4379-9bbc-02c6c58350c9"
          #github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload files to SCA Tool and start scan on Testing-Server
        uses: scatool/github-action@v0.4.3
        with:
          api_url: http://10.131.64.77/api/v1/
          api_key: "sca2026-07-23toolYryZVHApYtLW5Bn8vgW9X8uvOhYXzduXm6w19vNLL30"
          project_id: "ccb33939-8634-48b2-9ed7-d4d9296508bf"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload files to SCA Tool and start scan on Staging-Server
        uses: scatool/github-action@v0.4.3
        with:
          api_url: https://staging.scatool.com/api/v1/
          api_key: "sca2026-07-24toolp1FMBjwRE-M--5NlAT26abzAhFvCFkBgJ4ZmmwYDiRk"
          project_id: "53042bac-cd52-44d8-b57b-cf68ee9c1102"
          github_token: ${{ secrets.GITHUB_TOKEN }}



          
